" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

Plug 'lervag/vimtex' " editing LaTex files

call plug#end()

execute pathogen#infect()

:set number
:set splitright
:set tabstop=4
:set shiftwidth=4
:set expandtab

map <C-n> :NERDTreeToggle<CR>
